<a href="https://colab.research.google.com/github/Taiba528/My-Python-World/blob/master/COVID_case_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from google.colab import files
uploaded=files.upload()

Saving covid_confirmed_daily_updates.csv to covid_confirmed_daily_updates.csv

In [3]:
df = pd.read_csv("covid_confirmed_daily_updates.csv")
df.head()

        Country/Region  1/22/20  1/23/20  ...  3/16/20  3/17/20  3/18/20
0          Afghanistan        0        0  ...       21       22       22
1              Albania        0        0  ...       51       55       59
2              Algeria        0        0  ...       54       60       74
3              Andorra        0        0  ...        2       39       39
4  Antigua and Barbuda        0        0  ...        1        1        1

[5 rows x 58 columns]

In [4]:
df.shape

(153, 58)

In [5]:
df[df['Country/Region']=='India']

   Country/Region  1/22/20  1/23/20  ...  3/16/20  3/17/20  3/18/20
63          India        0        0  ...      119      142      156

[1 rows x 58 columns]

In [0]:
def cal_moving_avg(input_df, window=2):
    """Calculates Moving avg using the window size."""
    _df = input_df.rolling(window, axis=1).median()['3/10/20']
    
    return _df

def cal_ewma(input_df, comm=0.3):
    """Calculates the exp wighted moving average using the window size."""
    _df = input_df.ewm(com=comm).mean()['3/10/20']
    
    return _df

In [0]:
all_pred_df = pd.DataFrame()
all_pred_df_ew = pd.DataFrame()

In [8]:
for df in [df, grp_reco_data_df, grp_death_data_df]:
    _df = cal_moving_avg(df, window=2)
    ew_df = cal_ewma(df, comm=0.4)
    all_pred_df = pd.concat([all_pred_df, _df], axis=1)
    all_pred_df_ew = pd.concat([all_pred_df_ew, ew_df], axis=1)

NameError: ignored

In [9]:
all_pred_df.columns =['Confirmed', 'Recovered', 'Death']    
all_pred_df_ew.columns =['Confirmed', 'Recovered', 'Death']

ValueError: ignored